<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOefdPYx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOefdPYx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOefdPYx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOefdPYx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOefdPYx\App_KernelDevDebugContainer([
    'container.build_hash' => 'OefdPYx',
    'container.build_id' => 'b5b2c554',
    'container.build_time' => 1659964891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOefdPYx');
