<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBgIomg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBgIomg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBgIomg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBgIomg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEBgIomg\App_KernelDevDebugContainer([
    'container.build_hash' => 'EBgIomg',
    'container.build_id' => '02ab22d2',
    'container.build_time' => 1659973896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBgIomg');
